### PR TITLE
Visualization

### PR DESCRIPTION
**Pull request by be-marc**
#6 

`plot.ResamplingSpCVBlock`, `plot.ResamplingSpCVEnv`, `plot.ResamplingSpCVKmeans` are the same. We could create a super class to just have one plotting function.  `plot.ResamplingSpCVBuffer` is different because it is a leave-one-out cross-validation, which cannot be visualized in the same way. 

- [x] Single fold plot
- [x] Single train-test plot
- [x] Multi train-test plot 
- [x] Unify redundant code

- [x] Update documentation

- [x] add tests

Examples are in `inst/mlr3spatiotemporal_test.R` at the end of the file.

### CODE REVIEW

**Comment by be-marc** [comment]
We have two different notes in the R CMD check.

``autoplot.ResamplingSpCVBlock: no visible binding for global variable
  ‘fold’ ``

These notes are related to `ggplot2` and `data.table` functions used in `S3` classes. The solution for `ggplot2` is to use `aes_string` instead of `aes`. Do we also have a solution for `data.table` functions? There are various [solutions](https://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when) but all seem a little bit hacky.

`` Unexported object imported by a ':::' call: ‘mlr3:::translate_types’ ``

We need the `translate_types` function in `TaskClassifST.R`. The function is located in `helper.R` in the `mlr3`  package. If we use `:::`, we get a note.

**Comment by pat-s** [comment]
1. I remember using "Add a call to globalVariables(c("x.values", "y.values")) somewhere in the top-level of your package." in the past but yeah, it is not nice.

    @mllg Whats your convention here?

2. @mllg 	Can we export `mlr3:::translate_types()`? Otherwise you (@be-marc) can copy it into this package and use it internally.

**Comment by pat-s** [comment]
The "undefined global variables" issue is a general problem with data.tables syntax and can be solved by https://github.com/Rdatatable/data.table/issues/850#issuecomment-259466153.

**Comment by pat-s** [comment]
I've added some improvements:

- Legend symbols are now points instead of squares
- The user can set `grid = FALSE` to only get the list of ggplot2 objects returned and do the grid-alignment manually
- Added a Label indicating the fold id of each subplot if multiple folds are plotted
- improved documentation

These changes have only been applied to `autoplot.ResamplingSpCVBlock()` so far. 

Maybe we can reduce the whitespace between the subplots. 
The axis labelling is automatic and is ok if the plot is stretched to a normal size. 
For publication ready plot one would use `grid = FALSE` anyways.

image

**Comment by pat-s** [comment]
@be-marc 	
- I unified the underlying plotting code into an internal function called `autoplot_spatial()`
- `autoplot.SpCVBuffer()` now works in the same way as the others due to some small magic
- Merged all documentation into a single .Rd file

Example of `autoplot.SpCVBuffer()`

image

**Comment by pat-s** [comment]
Thanks again Marc!

**Pull request merged**
